####MEDIA PLAYERS####
# Ran by using Kodi: https://kodi.tv/
- platform: kodi
  url: http://192.XXX.XXX.XXX:80/jsonrpc
  name: OSMC
#media_player 2:
#  platform: kodi
#  url: http://192.XXX.XXX.XXX:80/jsonrpc
#  name: KODI Stormtrooper
